services:
  api-entrypoint:
    build: ./api-entrypoint
    ports:
      - "3000:3000"
    env_file:
      - ./api-entrypoint/.env
    depends_on:
      - redis
      - rabbitmq
      - user-service
      - post-service
      - media-service
      - search-service
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672
      USER_SERVICE_URL: http://user-service:3001
      POST_SERVICE_URL: http://post-service:3002
      MEDIA_SERVICE_URL: http://media-service:3003
      SEARCH_SERVICE_URL: http://search-service:3004
    volumes:
      - ./api-entrypoint/src:/usr/src/app/src

  user-service:
    build: ./user-service
    env_file:
      - ./user-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672
    volumes:
      - ./user-service/src:/usr/src/app/src

  post-service:
    build: ./post-service
    env_file:
      - ./post-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672
    volumes:
      - ./post-service/src:/usr/src/app/src

  media-service:
    build: ./media-service
    env_file:
      - ./media-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672
    volumes:
      - ./media-service/src:/usr/src/app/src
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "api.cloudinary.com:44.223.246.183"

  search-service:
    build: ./search-service
    env_file:
      - ./search-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672
    volumes:
      - ./search-service/src:/usr/src/app/src

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    # ports:
    #   - "5672:5672"
    #   - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
